const constants = {
	SET_CONTROLLERS_TUNE:   							'SET_CONTROLLERS_TUNE',
	SET_CONTROLLERS_GLIDE:   							'SET_CONTROLLERS_GLIDE',
	SET_CONTROLLERS_MOD_MIX:  						'SET_CONTROLLERS_MOD_MIX',
	SET_CONTROLLERS_MOD_DEPTH:     				'SET_CONTROLLERS_MOD_DEPTH',
	SET_CONTROLLERS_LFO_RATE:   					'SET_CONTROLLERS_LFO_RATE'
}

export default constants
